# Generated by Django 3.0 on 2022-04-27 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('babysisters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='date when the object was created', verbose_name='creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='date when the object was modified', verbose_name='update date')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('document', models.CharField(default='', max_length=20, verbose_name='Document')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Phone')),
                ('direction', models.CharField(default='', max_length=100, verbose_name='Direction')),
                ('created_by', models.ForeignKey(blank=True, help_text='user who created the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creation user')),
                ('modified_by', models.ForeignKey(blank=True, help_text='user who performed the update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='update user')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babysisters.Schedule', verbose_name='Schedule')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
