# Generated by Django 3.0 on 2022-05-06 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BabySister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='date when the object was created', verbose_name='creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='date when the object was modified', verbose_name='update date')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Name')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='Last name')),
                ('document', models.CharField(default='', max_length=20, verbose_name='Document')),
                ('phone', models.CharField(default='', max_length=20, verbose_name='Phone')),
                ('date_b', models.DateField(null=True, verbose_name='Date birth')),
                ('created_by', models.ForeignKey(blank=True, help_text='user who created the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='babysister_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creation user')),
                ('modified_by', models.ForeignKey(blank=True, help_text='user who performed the update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='babysister_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='update user')),
            ],
            options={
                'verbose_name': 'Baby sister',
                'verbose_name_plural': 'Baby sisters',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='date when the object was created', verbose_name='creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='date when the object was modified', verbose_name='update date')),
                ('day', models.DateField(verbose_name='Day')),
                ('start_hour', models.TimeField(verbose_name='Start hour')),
                ('end_hour', models.TimeField(verbose_name='End hour')),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('baby_sister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='babysisters.BabySister', verbose_name='Baby sister')),
                ('created_by', models.ForeignKey(blank=True, help_text='user who created the object', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_created_by', to=settings.AUTH_USER_MODEL, verbose_name='creation user')),
                ('modified_by', models.ForeignKey(blank=True, help_text='user who performed the update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='update user')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
