# Generated by Django 3.0 on 2022-05-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babysisters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='state',
            field=models.BooleanField(default=True, verbose_name='State'),
        ),
    ]
